spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:C:/temp/db
    hikari:
      username: ""
      password: ""
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: update